### ISSUE TITLE
Please make harcoded items configurable

### ISSUE THREAD

**Issue by kajalelohai** [channikhabra/brandi#2]
I think following are the things need to be configurable :

1. Icons hover title
2. About me section
3. Removing any social options from `params.author` ex: stack-overflow should remove the icon from sidebar.

**Comment by bitspook** [comment]
I have changed this project from being a hugo theme to a hakyll based static site generator. I have some features planned that can make good use of hakyll and pandoc; and I want to get my hands dirty with haskell. Closing this issue since it is no longer relevant now.
